name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image and run a container
      run: docker-compose up -d --build
    - name: Tag the image
      run: docker tag jupyterhub wdracfan/jupyterhub
    - name: Push to DockerHub
      run: docker push wdracfan/jupyterhub
